require('cmp').register_source('form_options', require('cmp_form_options'))
require('cmp').register_source('html_class', require('cmp_html_class'))
require('cmp').register_source('symfony_routes', require('cmp_symfony_routes'))
require('cmp').register_source('symfony_translations', require('cmp_symfony_translations'))
require('cmp').register_source('twig', require('cmp_twig'))
require('cmp').register_source('twig_constants', require('cmp_twig_constants'))
